### ISSUE TITLE
I am trying to migrate a project from itext to openPdf

### ISSUE THREAD

**Issue by rajukumar17** [LibrePDF/OpenPDF#552]
java.lang.NoSuchMethodError: com.lowagie.text.pdf.PdfPTable.setComplete(Z)V

when i try to create a pdf i am getting this exception.the code is working fine in itext 5.0.6 version when i am changing to openpdf 1.3.26 version getting this exception.

java.lang.NoSuchMethodError: com.lowagie.text.pdf.PdfPTable.setComplete(Z)V.

**Comment by asturio** [comment]
Strange, than the method exists:

com.lowagie.text.pdf.PdfPTable#setComplete.


https://github.com/LibrePDF/OpenPDF/blob/bb764e0296db309a53baa1188195273cd4b24d54/openpdf/src/main/java/com/lowagie/text/pdf/PdfPTable.java#L1602

Please note, that for iText 5+ you should use https://github.com/LibrePDF/OpenPDF5

**Comment by mkl-public** [comment]
> Please note, that for iText 5+ you should use https://github.com/LibrePDF/OpenPDF5

That might not be possible if the OP switched to OpenPdf to avoid the AGPL...

**Comment by asturio** [comment]
> > Please note, that for iText 5+ you should use https://github.com/LibrePDF/OpenPDF5
> 
> That might not be possible if the OP switched to OpenPdf to avoid the AGPL...

Yes, that is true. And I just checked OpenPDF5. It recommends the usage of OpenPDF instead.

**Comment by rajukumar17** [comment]
I just solved that problem.there is a itext 2.0.6 dependency that caused the problem.i removed it and everything is working fine.tq..
